# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - python_version is defined
      - python_package_prefix is defined

- debug: var=python_version
  tags:
    - never
    - debug

- debug: var=python_package_prefix
  tags:
    - never
    - debug

- name: pip is installed
  when:
    - ansible_os_family != 'RedHat' or python_version == 2
  package:
    name: "{{ python_package_prefix[python_version] + '-' + 'pip' }}"
    state: present

- name: python is installed
  when:
    - ansible_os_family == 'RedHat' and python_version == 3
  include_role:
    name: python

- name: upgrade pip
  when: python_pip_upgrade
  pip:
    name: pip
    executable: pip{{ python_version }}
    extra_args: --upgrade
...
