# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - python2_package_prefix is defined

- debug: var=python2_package_prefix
  tags:
    - never
    - debug

- name: pip is installed
  package:
    name: "{{ python2_package_prefix + '-' + 'pip' }}"
    state: present

- name: upgrade pip
  when: python2_pip_upgrade
  pip:
    name: pip
    executable: pip2
    extra_args: --upgrade
...
