# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - python_version is defined
      - python_package_prefix is defined

- debug: var=python_version
  tags:
    - never
    - debug

- debug: var=python_package_prefix
  tags:
    - never
    - debug

- name: include OS specific tasks
  when:
    - python_version == 3    
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
  include_tasks:
    file: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: python is installed
  package:
    name: "{{ python_package_prefix[python_version] }}"
    state: present
...
